/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.41.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Connection } from './Connection';
import {
    ConnectionFromJSON,
    ConnectionFromJSONTyped,
    ConnectionToJSON,
} from './Connection';

/**
 * 
 * @export
 * @interface ConnectionsPage
 */
export interface ConnectionsPage {
    /**
     * The reference to the connection collection itself.
     * @type {string}
     * @memberof ConnectionsPage
     */
    self: string;
    /**
     * The type of object returned. In this case a `Collection`.
     * @type {string}
     * @memberof ConnectionsPage
     */
    kind: string;
    /**
     * Page number within the context of paginated response.
     * @type {string}
     * @memberof ConnectionsPage
     */
    pageOf: string;
    /**
     * URL of the next page (if available)
     * @type {string}
     * @memberof ConnectionsPage
     */
    next?: string;
    /**
     * URL of the previous page (if available)
     * @type {string}
     * @memberof ConnectionsPage
     */
    previous?: string;
    /**
     * The array containing the list of connection records.
     * @type {Array<Connection>}
     * @memberof ConnectionsPage
     */
    contents: Array<Connection>;
}

/**
 * Check if a given object implements the ConnectionsPage interface.
 */
export function instanceOfConnectionsPage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "self" in value;
    isInstance = isInstance && "kind" in value;
    isInstance = isInstance && "pageOf" in value;
    isInstance = isInstance && "contents" in value;

    return isInstance;
}

export function ConnectionsPageFromJSON(json: any): ConnectionsPage {
    return ConnectionsPageFromJSONTyped(json, false);
}

export function ConnectionsPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionsPage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'self': json['self'],
        'kind': json['kind'],
        'pageOf': json['pageOf'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'contents': ((json['contents'] as Array<any>).map(ConnectionFromJSON)),
    };
}

export function ConnectionsPageToJSON(value?: ConnectionsPage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'self': value.self,
        'kind': value.kind,
        'pageOf': value.pageOf,
        'next': value.next,
        'previous': value.previous,
        'contents': ((value.contents as Array<any>).map(ConnectionToJSON)),
    };
}

