/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.41.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Connection } from './Connection';
import {
    ConnectionFromJSON,
    ConnectionFromJSONTyped,
    ConnectionToJSON,
} from './Connection';

/**
 * 
 * @export
 * @interface ConnectionsPageAllOf
 */
export interface ConnectionsPageAllOf {
    /**
     * The array containing the list of connection records.
     * @type {Array<Connection>}
     * @memberof ConnectionsPageAllOf
     */
    contents: Array<Connection>;
}

/**
 * Check if a given object implements the ConnectionsPageAllOf interface.
 */
export function instanceOfConnectionsPageAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contents" in value;

    return isInstance;
}

export function ConnectionsPageAllOfFromJSON(json: any): ConnectionsPageAllOf {
    return ConnectionsPageAllOfFromJSONTyped(json, false);
}

export function ConnectionsPageAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionsPageAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contents': ((json['contents'] as Array<any>).map(ConnectionFromJSON)),
    };
}

export function ConnectionsPageAllOfToJSON(value?: ConnectionsPageAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contents': ((value.contents as Array<any>).map(ConnectionToJSON)),
    };
}

