/* tslint:disable */
/* eslint-disable */
/**
 * PrismAgent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateManagedDidRequestDocumentTemplate } from './CreateManagedDidRequestDocumentTemplate';
import {
    CreateManagedDidRequestDocumentTemplateFromJSON,
    CreateManagedDidRequestDocumentTemplateFromJSONTyped,
    CreateManagedDidRequestDocumentTemplateToJSON,
} from './CreateManagedDidRequestDocumentTemplate';

/**
 * 
 * @export
 * @interface CreateManagedDidRequest
 */
export interface CreateManagedDidRequest {
    /**
     * 
     * @type {CreateManagedDidRequestDocumentTemplate}
     * @memberof CreateManagedDidRequest
     */
    documentTemplate: CreateManagedDidRequestDocumentTemplate;
}

/**
 * Check if a given object implements the CreateManagedDidRequest interface.
 */
export function instanceOfCreateManagedDidRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "documentTemplate" in value;

    return isInstance;
}

export function CreateManagedDidRequestFromJSON(json: any): CreateManagedDidRequest {
    return CreateManagedDidRequestFromJSONTyped(json, false);
}

export function CreateManagedDidRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateManagedDidRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documentTemplate': CreateManagedDidRequestDocumentTemplateFromJSON(json['documentTemplate']),
    };
}

export function CreateManagedDidRequestToJSON(value?: CreateManagedDidRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'documentTemplate': CreateManagedDidRequestDocumentTemplateToJSON(value.documentTemplate),
    };
}

