/* tslint:disable */
/* eslint-disable */
/**
 * PrismAgent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateIssueCredentialRecordRequestAllOf
 */
export interface CreateIssueCredentialRecordRequestAllOf {
    /**
     * The issuer DID of the verifiable credential object.
     * @type {string}
     * @memberof CreateIssueCredentialRecordRequestAllOf
     */
    issuingDID: string;
    /**
     * The unique identifier of a DIDComm connection that already exists between the issuer and the holder, and that will be used to execute the issue credential protocol.
     * @type {string}
     * @memberof CreateIssueCredentialRecordRequestAllOf
     */
    connectionId: string;
}

/**
 * Check if a given object implements the CreateIssueCredentialRecordRequestAllOf interface.
 */
export function instanceOfCreateIssueCredentialRecordRequestAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "issuingDID" in value;
    isInstance = isInstance && "connectionId" in value;

    return isInstance;
}

export function CreateIssueCredentialRecordRequestAllOfFromJSON(json: any): CreateIssueCredentialRecordRequestAllOf {
    return CreateIssueCredentialRecordRequestAllOfFromJSONTyped(json, false);
}

export function CreateIssueCredentialRecordRequestAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIssueCredentialRecordRequestAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'issuingDID': json['issuingDID'],
        'connectionId': json['connectionId'],
    };
}

export function CreateIssueCredentialRecordRequestAllOfToJSON(value?: CreateIssueCredentialRecordRequestAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'issuingDID': value.issuingDID,
        'connectionId': value.connectionId,
    };
}

