/* tslint:disable */
/* eslint-disable */
/**
 * PrismAgent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DID } from './DID';
import {
    DIDFromJSON,
    DIDFromJSONTyped,
    DIDToJSON,
} from './DID';
import type { DIDDocumentMetadata } from './DIDDocumentMetadata';
import {
    DIDDocumentMetadataFromJSON,
    DIDDocumentMetadataFromJSONTyped,
    DIDDocumentMetadataToJSON,
} from './DIDDocumentMetadata';

/**
 * 
 * @export
 * @interface DIDResponse
 */
export interface DIDResponse {
    /**
     * 
     * @type {DID}
     * @memberof DIDResponse
     */
    did: DID;
    /**
     * 
     * @type {DIDDocumentMetadata}
     * @memberof DIDResponse
     */
    metadata: DIDDocumentMetadata;
}

/**
 * Check if a given object implements the DIDResponse interface.
 */
export function instanceOfDIDResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "did" in value;
    isInstance = isInstance && "metadata" in value;

    return isInstance;
}

export function DIDResponseFromJSON(json: any): DIDResponse {
    return DIDResponseFromJSONTyped(json, false);
}

export function DIDResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DIDResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'did': DIDFromJSON(json['did']),
        'metadata': DIDDocumentMetadataFromJSON(json['metadata']),
    };
}

export function DIDResponseToJSON(value?: DIDResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'did': DIDToJSON(value.did),
        'metadata': DIDDocumentMetadataToJSON(value.metadata),
    };
}

