/* tslint:disable */
/* eslint-disable */
/**
 * PrismAgent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An issue credential record to store the state of the protocol execution
 * @export
 * @interface IssueCredentialRecord
 */
export interface IssueCredentialRecord {
    /**
     * Identifier of the VC Schema associated with this object
     * @type {string}
     * @memberof IssueCredentialRecord
     */
    schemaId?: string;
    /**
     * Subject DID of the verifiable credentials object
     * @type {string}
     * @memberof IssueCredentialRecord
     */
    subjectId: string;
    /**
     * The validity period in seconds of the verifiable credential
     * @type {number}
     * @memberof IssueCredentialRecord
     */
    validityPeriod?: number;
    /**
     * Claims that will be associated with given verifiable credentials
     * @type {{ [key: string]: string; }}
     * @memberof IssueCredentialRecord
     */
    claims: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof IssueCredentialRecord
     */
    automaticIssuance?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IssueCredentialRecord
     */
    awaitConfirmation?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IssueCredentialRecord
     */
    recordId: string;
    /**
     * 
     * @type {Date}
     * @memberof IssueCredentialRecord
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof IssueCredentialRecord
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof IssueCredentialRecord
     */
    role: IssueCredentialRecordRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof IssueCredentialRecord
     */
    protocolState: IssueCredentialRecordProtocolStateEnum;
    /**
     * 
     * @type {string}
     * @memberof IssueCredentialRecord
     */
    publicationState?: IssueCredentialRecordPublicationStateEnum;
    /**
     * 
     * @type {string}
     * @memberof IssueCredentialRecord
     */
    jwtCredential?: string;
}


/**
 * @export
 */
export const IssueCredentialRecordRoleEnum = {
    Issuer: 'Issuer',
    Holder: 'Holder'
} as const;
export type IssueCredentialRecordRoleEnum = typeof IssueCredentialRecordRoleEnum[keyof typeof IssueCredentialRecordRoleEnum];

/**
 * @export
 */
export const IssueCredentialRecordProtocolStateEnum = {
    OfferPending: 'OfferPending',
    OfferSent: 'OfferSent',
    OfferReceived: 'OfferReceived',
    RequestPending: 'RequestPending',
    RequestSent: 'RequestSent',
    RequestReceived: 'RequestReceived',
    ProblemReportPending: 'ProblemReportPending',
    ProblemReportSent: 'ProblemReportSent',
    ProblemReportReceived: 'ProblemReportReceived',
    CredentialPending: 'CredentialPending',
    CredentialSent: 'CredentialSent',
    CredentialReceived: 'CredentialReceived'
} as const;
export type IssueCredentialRecordProtocolStateEnum = typeof IssueCredentialRecordProtocolStateEnum[keyof typeof IssueCredentialRecordProtocolStateEnum];

/**
 * @export
 */
export const IssueCredentialRecordPublicationStateEnum = {
    PublicationPending: 'PublicationPending',
    PublicationQueued: 'PublicationQueued',
    Published: 'Published'
} as const;
export type IssueCredentialRecordPublicationStateEnum = typeof IssueCredentialRecordPublicationStateEnum[keyof typeof IssueCredentialRecordPublicationStateEnum];


/**
 * Check if a given object implements the IssueCredentialRecord interface.
 */
export function instanceOfIssueCredentialRecord(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "subjectId" in value;
    isInstance = isInstance && "claims" in value;
    isInstance = isInstance && "recordId" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "role" in value;
    isInstance = isInstance && "protocolState" in value;

    return isInstance;
}

export function IssueCredentialRecordFromJSON(json: any): IssueCredentialRecord {
    return IssueCredentialRecordFromJSONTyped(json, false);
}

export function IssueCredentialRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueCredentialRecord {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schemaId': !exists(json, 'schemaId') ? undefined : json['schemaId'],
        'subjectId': json['subjectId'],
        'validityPeriod': !exists(json, 'validityPeriod') ? undefined : json['validityPeriod'],
        'claims': json['claims'],
        'automaticIssuance': !exists(json, 'automaticIssuance') ? undefined : json['automaticIssuance'],
        'awaitConfirmation': !exists(json, 'awaitConfirmation') ? undefined : json['awaitConfirmation'],
        'recordId': json['recordId'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'role': json['role'],
        'protocolState': json['protocolState'],
        'publicationState': !exists(json, 'publicationState') ? undefined : json['publicationState'],
        'jwtCredential': !exists(json, 'jwtCredential') ? undefined : json['jwtCredential'],
    };
}

export function IssueCredentialRecordToJSON(value?: IssueCredentialRecord | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schemaId': value.schemaId,
        'subjectId': value.subjectId,
        'validityPeriod': value.validityPeriod,
        'claims': value.claims,
        'automaticIssuance': value.automaticIssuance,
        'awaitConfirmation': value.awaitConfirmation,
        'recordId': value.recordId,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'role': value.role,
        'protocolState': value.protocolState,
        'publicationState': value.publicationState,
        'jwtCredential': value.jwtCredential,
    };
}

