/* tslint:disable */
/* eslint-disable */
/**
 * PrismAgent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IssueCredentialRecord } from './IssueCredentialRecord';
import {
    IssueCredentialRecordFromJSON,
    IssueCredentialRecordFromJSONTyped,
    IssueCredentialRecordToJSON,
} from './IssueCredentialRecord';

/**
 * A collection of issue credential records
 * @export
 * @interface IssueCredentialRecordCollection
 */
export interface IssueCredentialRecordCollection {
    /**
     * 
     * @type {Array<IssueCredentialRecord>}
     * @memberof IssueCredentialRecordCollection
     */
    items: Array<IssueCredentialRecord>;
    /**
     * 
     * @type {number}
     * @memberof IssueCredentialRecordCollection
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof IssueCredentialRecordCollection
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof IssueCredentialRecordCollection
     */
    count: number;
}

/**
 * Check if a given object implements the IssueCredentialRecordCollection interface.
 */
export function instanceOfIssueCredentialRecordCollection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "items" in value;
    isInstance = isInstance && "offset" in value;
    isInstance = isInstance && "limit" in value;
    isInstance = isInstance && "count" in value;

    return isInstance;
}

export function IssueCredentialRecordCollectionFromJSON(json: any): IssueCredentialRecordCollection {
    return IssueCredentialRecordCollectionFromJSONTyped(json, false);
}

export function IssueCredentialRecordCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueCredentialRecordCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(IssueCredentialRecordFromJSON)),
        'offset': json['offset'],
        'limit': json['limit'],
        'count': json['count'],
    };
}

export function IssueCredentialRecordCollectionToJSON(value?: IssueCredentialRecordCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(IssueCredentialRecordToJSON)),
        'offset': value.offset,
        'limit': value.limit,
        'count': value.count,
    };
}

