/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.41.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IssueCredentialRecord } from './IssueCredentialRecord';
import {
    IssueCredentialRecordFromJSON,
    IssueCredentialRecordFromJSONTyped,
    IssueCredentialRecordToJSON,
} from './IssueCredentialRecord';

/**
 * 
 * @export
 * @interface IssueCredentialRecordPageAllOf
 */
export interface IssueCredentialRecordPageAllOf {
    /**
     * 
     * @type {Array<IssueCredentialRecord>}
     * @memberof IssueCredentialRecordPageAllOf
     */
    contents: Array<IssueCredentialRecord>;
}

/**
 * Check if a given object implements the IssueCredentialRecordPageAllOf interface.
 */
export function instanceOfIssueCredentialRecordPageAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contents" in value;

    return isInstance;
}

export function IssueCredentialRecordPageAllOfFromJSON(json: any): IssueCredentialRecordPageAllOf {
    return IssueCredentialRecordPageAllOfFromJSONTyped(json, false);
}

export function IssueCredentialRecordPageAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueCredentialRecordPageAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contents': ((json['contents'] as Array<any>).map(IssueCredentialRecordFromJSON)),
    };
}

export function IssueCredentialRecordPageAllOfToJSON(value?: IssueCredentialRecordPageAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contents': ((value.contents as Array<any>).map(IssueCredentialRecordToJSON)),
    };
}

