/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.41.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IssueCredentialRecord } from './IssueCredentialRecord';
import {
    IssueCredentialRecordFromJSON,
    IssueCredentialRecordFromJSONTyped,
    IssueCredentialRecordToJSON,
} from './IssueCredentialRecord';

/**
 * 
 * @export
 * @interface IssueCredentialRecordPage
 */
export interface IssueCredentialRecordPage {
    /**
     * The reference to the connection collection itself.
     * @type {string}
     * @memberof IssueCredentialRecordPage
     */
    self: string;
    /**
     * The type of object returned. In this case a `Collection`.
     * @type {string}
     * @memberof IssueCredentialRecordPage
     */
    kind: string;
    /**
     * Page number within the context of paginated response.
     * @type {string}
     * @memberof IssueCredentialRecordPage
     */
    pageOf: string;
    /**
     * URL of the next page (if available)
     * @type {string}
     * @memberof IssueCredentialRecordPage
     */
    next?: string;
    /**
     * URL of the previous page (if available)
     * @type {string}
     * @memberof IssueCredentialRecordPage
     */
    previous?: string;
    /**
     * 
     * @type {Array<IssueCredentialRecord>}
     * @memberof IssueCredentialRecordPage
     */
    contents: Array<IssueCredentialRecord>;
}

/**
 * Check if a given object implements the IssueCredentialRecordPage interface.
 */
export function instanceOfIssueCredentialRecordPage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "self" in value;
    isInstance = isInstance && "kind" in value;
    isInstance = isInstance && "pageOf" in value;
    isInstance = isInstance && "contents" in value;

    return isInstance;
}

export function IssueCredentialRecordPageFromJSON(json: any): IssueCredentialRecordPage {
    return IssueCredentialRecordPageFromJSONTyped(json, false);
}

export function IssueCredentialRecordPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueCredentialRecordPage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'self': json['self'],
        'kind': json['kind'],
        'pageOf': json['pageOf'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'contents': ((json['contents'] as Array<any>).map(IssueCredentialRecordFromJSON)),
    };
}

export function IssueCredentialRecordPageToJSON(value?: IssueCredentialRecordPage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'self': value.self,
        'kind': value.kind,
        'pageOf': value.pageOf,
        'next': value.next,
        'previous': value.previous,
        'contents': ((value.contents as Array<any>).map(IssueCredentialRecordToJSON)),
    };
}

