/* tslint:disable */
/* eslint-disable */
/**
 * PrismAgent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IssueCredentialRecord } from './IssueCredentialRecord';
import {
    IssueCredentialRecordFromJSON,
    IssueCredentialRecordFromJSONTyped,
    IssueCredentialRecordToJSON,
} from './IssueCredentialRecord';

/**
 * A collection of issue credential records.
 * @export
 * @interface IssueCredentialRecordCollection
 */
export interface IssueCredentialRecordCollection {
    /**
     * The array containing the list of issue credential records.
     * @type {Array<IssueCredentialRecord>}
     * @memberof IssueCredentialRecordCollection
     */
    contents: Array<IssueCredentialRecord>;
}

/**
 * Check if a given object implements the IssueCredentialRecordCollection interface.
 */
export function instanceOfIssueCredentialRecordCollection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contents" in value;

    return isInstance;
}

export function IssueCredentialRecordCollectionFromJSON(json: any): IssueCredentialRecordCollection {
    return IssueCredentialRecordCollectionFromJSONTyped(json, false);
}

export function IssueCredentialRecordCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueCredentialRecordCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contents': ((json['contents'] as Array<any>).map(IssueCredentialRecordFromJSON)),
    };
}

export function IssueCredentialRecordCollectionToJSON(value?: IssueCredentialRecordCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contents': ((value.contents as Array<any>).map(IssueCredentialRecordToJSON)),
    };
}

