/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.41.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ManagedDID
 */
export interface ManagedDID {
    /**
     * 
     * @type {string}
     * @memberof ManagedDID
     */
    did: string;
    /**
     * A long-form DID. Mandatory when status is not PUBLISHED and optional when status is PUBLISHED
     * @type {string}
     * @memberof ManagedDID
     */
    longFormDid?: string;
    /**
     * A status indicating a publication state of a DID in the wallet (e.g. PUBLICATION_PENDING, PUBLISHED).
     * Does not represent DID a full lifecyle (e.g. deactivated, recovered, updated).
     * @type {string}
     * @memberof ManagedDID
     */
    status: ManagedDIDStatusEnum;
}


/**
 * @export
 */
export const ManagedDIDStatusEnum = {
    Created: 'CREATED',
    PublicationPending: 'PUBLICATION_PENDING',
    Published: 'PUBLISHED'
} as const;
export type ManagedDIDStatusEnum = typeof ManagedDIDStatusEnum[keyof typeof ManagedDIDStatusEnum];


/**
 * Check if a given object implements the ManagedDID interface.
 */
export function instanceOfManagedDID(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "did" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function ManagedDIDFromJSON(json: any): ManagedDID {
    return ManagedDIDFromJSONTyped(json, false);
}

export function ManagedDIDFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedDID {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'did': json['did'],
        'longFormDid': !exists(json, 'longFormDid') ? undefined : json['longFormDid'],
        'status': json['status'],
    };
}

export function ManagedDIDToJSON(value?: ManagedDID | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'did': value.did,
        'longFormDid': value.longFormDid,
        'status': value.status,
    };
}

