/* tslint:disable */
/* eslint-disable */
/**
 * PrismAgent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProofRequestAux } from './ProofRequestAux';
import {
    ProofRequestAuxFromJSON,
    ProofRequestAuxFromJSONTyped,
    ProofRequestAuxToJSON,
} from './ProofRequestAux';

/**
 * Presentation Status
 * @export
 * @interface PresentationStatus
 */
export interface PresentationStatus {
    /**
     * 
     * @type {string}
     * @memberof PresentationStatus
     */
    presentationId: string;
    /**
     * 
     * @type {string}
     * @memberof PresentationStatus
     */
    status: string;
    /**
     * 
     * @type {Array<ProofRequestAux>}
     * @memberof PresentationStatus
     */
    proofs: Array<ProofRequestAux>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PresentationStatus
     */
    data: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PresentationStatus
     */
    connectionId?: string;
}

/**
 * Check if a given object implements the PresentationStatus interface.
 */
export function instanceOfPresentationStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "presentationId" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "proofs" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function PresentationStatusFromJSON(json: any): PresentationStatus {
    return PresentationStatusFromJSONTyped(json, false);
}

export function PresentationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresentationStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'presentationId': json['presentationId'],
        'status': json['status'],
        'proofs': ((json['proofs'] as Array<any>).map(ProofRequestAuxFromJSON)),
        'data': json['data'],
        'connectionId': !exists(json, 'connectionId') ? undefined : json['connectionId'],
    };
}

export function PresentationStatusToJSON(value?: PresentationStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'presentationId': value.presentationId,
        'status': value.status,
        'proofs': ((value.proofs as Array<any>).map(ProofRequestAuxToJSON)),
        'data': value.data,
        'connectionId': value.connectionId,
    };
}

