/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.41.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PresentationStatus } from './PresentationStatus';
import {
    PresentationStatusFromJSON,
    PresentationStatusFromJSONTyped,
    PresentationStatusToJSON,
} from './PresentationStatus';

/**
 * 
 * @export
 * @interface PresentationStatusPageAllOf
 */
export interface PresentationStatusPageAllOf {
    /**
     * 
     * @type {Array<PresentationStatus>}
     * @memberof PresentationStatusPageAllOf
     */
    contents: Array<PresentationStatus>;
}

/**
 * Check if a given object implements the PresentationStatusPageAllOf interface.
 */
export function instanceOfPresentationStatusPageAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contents" in value;

    return isInstance;
}

export function PresentationStatusPageAllOfFromJSON(json: any): PresentationStatusPageAllOf {
    return PresentationStatusPageAllOfFromJSONTyped(json, false);
}

export function PresentationStatusPageAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresentationStatusPageAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contents': ((json['contents'] as Array<any>).map(PresentationStatusFromJSON)),
    };
}

export function PresentationStatusPageAllOfToJSON(value?: PresentationStatusPageAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contents': ((value.contents as Array<any>).map(PresentationStatusToJSON)),
    };
}

