/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.41.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProofRequestAux
 */
export interface ProofRequestAux {
    /**
     * The unique identifier of a schema the VC should comply with.
     * @type {string}
     * @memberof ProofRequestAux
     */
    schemaId: string;
    /**
     * One or more issuers that are trusted by the verifier emitting the proof presentation request.
     * @type {Array<string>}
     * @memberof ProofRequestAux
     */
    trustIssuers: Array<string>;
}

/**
 * Check if a given object implements the ProofRequestAux interface.
 */
export function instanceOfProofRequestAux(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "schemaId" in value;
    isInstance = isInstance && "trustIssuers" in value;

    return isInstance;
}

export function ProofRequestAuxFromJSON(json: any): ProofRequestAux {
    return ProofRequestAuxFromJSONTyped(json, false);
}

export function ProofRequestAuxFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProofRequestAux {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schemaId': json['schemaId'],
        'trustIssuers': json['trustIssuers'],
    };
}

export function ProofRequestAuxToJSON(value?: ProofRequestAux | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schemaId': value.schemaId,
        'trustIssuers': value.trustIssuers,
    };
}

