/* tslint:disable */
/* eslint-disable */
/**
 * PrismAgent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Revocation status record
 * @export
 * @interface RevocationStatus
 */
export interface RevocationStatus {
    /**
     * Operation id
     * @type {string}
     * @memberof RevocationStatus
     */
    id?: string;
    /**
     * Operation status
     * @type {string}
     * @memberof RevocationStatus
     */
    status?: RevocationStatusStatusEnum;
}


/**
 * @export
 */
export const RevocationStatusStatusEnum = {
    Scheduled: 'scheduled',
    Pending: 'pending',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type RevocationStatusStatusEnum = typeof RevocationStatusStatusEnum[keyof typeof RevocationStatusStatusEnum];


/**
 * Check if a given object implements the RevocationStatus interface.
 */
export function instanceOfRevocationStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RevocationStatusFromJSON(json: any): RevocationStatus {
    return RevocationStatusFromJSONTyped(json, false);
}

export function RevocationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevocationStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function RevocationStatusToJSON(value?: RevocationStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'status': value.status,
    };
}

