/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.41.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ManagedDIDKeyTemplate } from './ManagedDIDKeyTemplate';
import {
    ManagedDIDKeyTemplateFromJSON,
    ManagedDIDKeyTemplateFromJSONTyped,
    ManagedDIDKeyTemplateToJSON,
} from './ManagedDIDKeyTemplate';
import type { Service } from './Service';
import {
    ServiceFromJSON,
    ServiceFromJSONTyped,
    ServiceToJSON,
} from './Service';
import type { UpdateManagedDIDRequestActionsInnerRemoveKey } from './UpdateManagedDIDRequestActionsInnerRemoveKey';
import {
    UpdateManagedDIDRequestActionsInnerRemoveKeyFromJSON,
    UpdateManagedDIDRequestActionsInnerRemoveKeyFromJSONTyped,
    UpdateManagedDIDRequestActionsInnerRemoveKeyToJSON,
} from './UpdateManagedDIDRequestActionsInnerRemoveKey';
import type { UpdateManagedDIDRequestActionsInnerRemoveService } from './UpdateManagedDIDRequestActionsInnerRemoveService';
import {
    UpdateManagedDIDRequestActionsInnerRemoveServiceFromJSON,
    UpdateManagedDIDRequestActionsInnerRemoveServiceFromJSONTyped,
    UpdateManagedDIDRequestActionsInnerRemoveServiceToJSON,
} from './UpdateManagedDIDRequestActionsInnerRemoveService';
import type { UpdateManagedDIDRequestActionsInnerUpdateService } from './UpdateManagedDIDRequestActionsInnerUpdateService';
import {
    UpdateManagedDIDRequestActionsInnerUpdateServiceFromJSON,
    UpdateManagedDIDRequestActionsInnerUpdateServiceFromJSONTyped,
    UpdateManagedDIDRequestActionsInnerUpdateServiceToJSON,
} from './UpdateManagedDIDRequestActionsInnerUpdateService';

/**
 * Detail of DID update action. Only property matching actionType can be present.
 * @export
 * @interface UpdateManagedDIDRequestActionsInner
 */
export interface UpdateManagedDIDRequestActionsInner {
    /**
     * 
     * @type {string}
     * @memberof UpdateManagedDIDRequestActionsInner
     */
    actionType: UpdateManagedDIDRequestActionsInnerActionTypeEnum;
    /**
     * 
     * @type {ManagedDIDKeyTemplate}
     * @memberof UpdateManagedDIDRequestActionsInner
     */
    addKey?: ManagedDIDKeyTemplate;
    /**
     * 
     * @type {UpdateManagedDIDRequestActionsInnerRemoveKey}
     * @memberof UpdateManagedDIDRequestActionsInner
     */
    removeKey?: UpdateManagedDIDRequestActionsInnerRemoveKey;
    /**
     * 
     * @type {Service}
     * @memberof UpdateManagedDIDRequestActionsInner
     */
    addService?: Service;
    /**
     * 
     * @type {UpdateManagedDIDRequestActionsInnerRemoveService}
     * @memberof UpdateManagedDIDRequestActionsInner
     */
    removeService?: UpdateManagedDIDRequestActionsInnerRemoveService;
    /**
     * 
     * @type {UpdateManagedDIDRequestActionsInnerUpdateService}
     * @memberof UpdateManagedDIDRequestActionsInner
     */
    updateService?: UpdateManagedDIDRequestActionsInnerUpdateService;
}


/**
 * @export
 */
export const UpdateManagedDIDRequestActionsInnerActionTypeEnum = {
    AddKey: 'ADD_KEY',
    RemoveKey: 'REMOVE_KEY',
    AddService: 'ADD_SERVICE',
    RemoveService: 'REMOVE_SERVICE',
    UpdateService: 'UPDATE_SERVICE'
} as const;
export type UpdateManagedDIDRequestActionsInnerActionTypeEnum = typeof UpdateManagedDIDRequestActionsInnerActionTypeEnum[keyof typeof UpdateManagedDIDRequestActionsInnerActionTypeEnum];


/**
 * Check if a given object implements the UpdateManagedDIDRequestActionsInner interface.
 */
export function instanceOfUpdateManagedDIDRequestActionsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "actionType" in value;

    return isInstance;
}

export function UpdateManagedDIDRequestActionsInnerFromJSON(json: any): UpdateManagedDIDRequestActionsInner {
    return UpdateManagedDIDRequestActionsInnerFromJSONTyped(json, false);
}

export function UpdateManagedDIDRequestActionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateManagedDIDRequestActionsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'actionType': json['actionType'],
        'addKey': !exists(json, 'addKey') ? undefined : ManagedDIDKeyTemplateFromJSON(json['addKey']),
        'removeKey': !exists(json, 'removeKey') ? undefined : UpdateManagedDIDRequestActionsInnerRemoveKeyFromJSON(json['removeKey']),
        'addService': !exists(json, 'addService') ? undefined : ServiceFromJSON(json['addService']),
        'removeService': !exists(json, 'removeService') ? undefined : UpdateManagedDIDRequestActionsInnerRemoveServiceFromJSON(json['removeService']),
        'updateService': !exists(json, 'updateService') ? undefined : UpdateManagedDIDRequestActionsInnerUpdateServiceFromJSON(json['updateService']),
    };
}

export function UpdateManagedDIDRequestActionsInnerToJSON(value?: UpdateManagedDIDRequestActionsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'actionType': value.actionType,
        'addKey': ManagedDIDKeyTemplateToJSON(value.addKey),
        'removeKey': UpdateManagedDIDRequestActionsInnerRemoveKeyToJSON(value.removeKey),
        'addService': ServiceToJSON(value.addService),
        'removeService': UpdateManagedDIDRequestActionsInnerRemoveServiceToJSON(value.removeService),
        'updateService': UpdateManagedDIDRequestActionsInnerUpdateServiceToJSON(value.updateService),
    };
}

