/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.41.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateManagedDIDRequestActionsInnerRemoveService
 */
export interface UpdateManagedDIDRequestActionsInnerRemoveService {
    /**
     * ID of service to remove from DID document
     * @type {string}
     * @memberof UpdateManagedDIDRequestActionsInnerRemoveService
     */
    id: string;
}

/**
 * Check if a given object implements the UpdateManagedDIDRequestActionsInnerRemoveService interface.
 */
export function instanceOfUpdateManagedDIDRequestActionsInnerRemoveService(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function UpdateManagedDIDRequestActionsInnerRemoveServiceFromJSON(json: any): UpdateManagedDIDRequestActionsInnerRemoveService {
    return UpdateManagedDIDRequestActionsInnerRemoveServiceFromJSONTyped(json, false);
}

export function UpdateManagedDIDRequestActionsInnerRemoveServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateManagedDIDRequestActionsInnerRemoveService {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function UpdateManagedDIDRequestActionsInnerRemoveServiceToJSON(value?: UpdateManagedDIDRequestActionsInnerRemoveService | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

