/* tslint:disable */
/* eslint-disable */
/**
 * PrismAgent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateManagedDIDRequestActionsInnerRemoveKey
 */
export interface UpdateManagedDIDRequestActionsInnerRemoveKey {
    /**
     * ID of key to remove from DID document
     * @type {string}
     * @memberof UpdateManagedDIDRequestActionsInnerRemoveKey
     */
    id: string;
}

/**
 * Check if a given object implements the UpdateManagedDIDRequestActionsInnerRemoveKey interface.
 */
export function instanceOfUpdateManagedDIDRequestActionsInnerRemoveKey(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function UpdateManagedDIDRequestActionsInnerRemoveKeyFromJSON(json: any): UpdateManagedDIDRequestActionsInnerRemoveKey {
    return UpdateManagedDIDRequestActionsInnerRemoveKeyFromJSONTyped(json, false);
}

export function UpdateManagedDIDRequestActionsInnerRemoveKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateManagedDIDRequestActionsInnerRemoveKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function UpdateManagedDIDRequestActionsInnerRemoveKeyToJSON(value?: UpdateManagedDIDRequestActionsInnerRemoveKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

