/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.41.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A patch to existing Service. 'type' and 'serviceEndpoint' can't both be empty.
 * @export
 * @interface UpdateManagedDIDRequestActionsInnerUpdateService
 */
export interface UpdateManagedDIDRequestActionsInnerUpdateService {
    /**
     * ID of existing service to update in the DID document
     * @type {string}
     * @memberof UpdateManagedDIDRequestActionsInnerUpdateService
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateManagedDIDRequestActionsInnerUpdateService
     */
    type?: UpdateManagedDIDRequestActionsInnerUpdateServiceTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateManagedDIDRequestActionsInnerUpdateService
     */
    serviceEndpoint?: Array<string>;
}


/**
 * @export
 */
export const UpdateManagedDIDRequestActionsInnerUpdateServiceTypeEnum = {
    LinkedDomains: 'LinkedDomains'
} as const;
export type UpdateManagedDIDRequestActionsInnerUpdateServiceTypeEnum = typeof UpdateManagedDIDRequestActionsInnerUpdateServiceTypeEnum[keyof typeof UpdateManagedDIDRequestActionsInnerUpdateServiceTypeEnum];


/**
 * Check if a given object implements the UpdateManagedDIDRequestActionsInnerUpdateService interface.
 */
export function instanceOfUpdateManagedDIDRequestActionsInnerUpdateService(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function UpdateManagedDIDRequestActionsInnerUpdateServiceFromJSON(json: any): UpdateManagedDIDRequestActionsInnerUpdateService {
    return UpdateManagedDIDRequestActionsInnerUpdateServiceFromJSONTyped(json, false);
}

export function UpdateManagedDIDRequestActionsInnerUpdateServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateManagedDIDRequestActionsInnerUpdateService {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'serviceEndpoint': !exists(json, 'serviceEndpoint') ? undefined : json['serviceEndpoint'],
    };
}

export function UpdateManagedDIDRequestActionsInnerUpdateServiceToJSON(value?: UpdateManagedDIDRequestActionsInnerUpdateService | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'serviceEndpoint': value.serviceEndpoint,
    };
}

