/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.41.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateManagedDIDRequestActionsInner } from './UpdateManagedDIDRequestActionsInner';
import {
    UpdateManagedDIDRequestActionsInnerFromJSON,
    UpdateManagedDIDRequestActionsInnerFromJSONTyped,
    UpdateManagedDIDRequestActionsInnerToJSON,
} from './UpdateManagedDIDRequestActionsInner';

/**
 * 
 * @export
 * @interface UpdateManagedDIDRequest
 */
export interface UpdateManagedDIDRequest {
    /**
     * A list of actions to perform on DID document.
     * The field `addKey`, `removeKey`, `addService`, `removeService`, `updateService` must corresponds to
     * the `actionType` specified. For example, `addKey` must be present when `actionType` is `ADD_KEY`.
     * @type {Array<UpdateManagedDIDRequestActionsInner>}
     * @memberof UpdateManagedDIDRequest
     */
    actions: Array<UpdateManagedDIDRequestActionsInner>;
}

/**
 * Check if a given object implements the UpdateManagedDIDRequest interface.
 */
export function instanceOfUpdateManagedDIDRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "actions" in value;

    return isInstance;
}

export function UpdateManagedDIDRequestFromJSON(json: any): UpdateManagedDIDRequest {
    return UpdateManagedDIDRequestFromJSONTyped(json, false);
}

export function UpdateManagedDIDRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateManagedDIDRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'actions': ((json['actions'] as Array<any>).map(UpdateManagedDIDRequestActionsInnerFromJSON)),
    };
}

export function UpdateManagedDIDRequestToJSON(value?: UpdateManagedDIDRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'actions': ((value.actions as Array<any>).map(UpdateManagedDIDRequestActionsInnerToJSON)),
    };
}

