/* tslint:disable */
/* eslint-disable */
/**
 * Prism Agent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.41.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VerificationPolicy } from './VerificationPolicy';
import {
    VerificationPolicyFromJSON,
    VerificationPolicyFromJSONTyped,
    VerificationPolicyToJSON,
} from './VerificationPolicy';

/**
 * 
 * @export
 * @interface VerificationPolicyPageAllOf
 */
export interface VerificationPolicyPageAllOf {
    /**
     * 
     * @type {Array<VerificationPolicy>}
     * @memberof VerificationPolicyPageAllOf
     */
    contents: Array<VerificationPolicy>;
}

/**
 * Check if a given object implements the VerificationPolicyPageAllOf interface.
 */
export function instanceOfVerificationPolicyPageAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contents" in value;

    return isInstance;
}

export function VerificationPolicyPageAllOfFromJSON(json: any): VerificationPolicyPageAllOf {
    return VerificationPolicyPageAllOfFromJSONTyped(json, false);
}

export function VerificationPolicyPageAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationPolicyPageAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contents': ((json['contents'] as Array<any>).map(VerificationPolicyFromJSON)),
    };
}

export function VerificationPolicyPageAllOfToJSON(value?: VerificationPolicyPageAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contents': ((value.contents as Array<any>).map(VerificationPolicyToJSON)),
    };
}

