/* tslint:disable */
/* eslint-disable */
/**
 * PrismAgent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RevocationStatus } from './RevocationStatus';
import {
    RevocationStatusFromJSON,
    RevocationStatusFromJSONTyped,
    RevocationStatusToJSON,
} from './RevocationStatus';

/**
 * Credential revocation response. Contain credential id and revocation operation for tracing the completion
 * @export
 * @interface W3CCredentialRevocationResponse
 */
export interface W3CCredentialRevocationResponse {
    /**
     * Credential identity
     * @type {string}
     * @memberof W3CCredentialRevocationResponse
     */
    credentialId: string;
    /**
     * 
     * @type {RevocationStatus}
     * @memberof W3CCredentialRevocationResponse
     */
    operation?: RevocationStatus;
}

/**
 * Check if a given object implements the W3CCredentialRevocationResponse interface.
 */
export function instanceOfW3CCredentialRevocationResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "credentialId" in value;

    return isInstance;
}

export function W3CCredentialRevocationResponseFromJSON(json: any): W3CCredentialRevocationResponse {
    return W3CCredentialRevocationResponseFromJSONTyped(json, false);
}

export function W3CCredentialRevocationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): W3CCredentialRevocationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'credentialId': json['credentialId'],
        'operation': !exists(json, 'operation') ? undefined : RevocationStatusFromJSON(json['operation']),
    };
}

export function W3CCredentialRevocationResponseToJSON(value?: W3CCredentialRevocationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'credentialId': value.credentialId,
        'operation': RevocationStatusToJSON(value.operation),
    };
}

