/* tslint:disable */
/* eslint-disable */
/**
 * PrismAgent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Verifiable Credential revocation status
 * @export
 * @interface W3CCredentialStatus
 */
export interface W3CCredentialStatus {
    /**
     * Status name
     * @type {string}
     * @memberof W3CCredentialStatus
     */
    status: W3CCredentialStatusStatusEnum;
    /**
     * Description about the status
     * @type {string}
     * @memberof W3CCredentialStatus
     */
    description?: string;
}


/**
 * @export
 */
export const W3CCredentialStatusStatusEnum = {
    Issued: 'issued',
    Revoked: 'revoked'
} as const;
export type W3CCredentialStatusStatusEnum = typeof W3CCredentialStatusStatusEnum[keyof typeof W3CCredentialStatusStatusEnum];


/**
 * Check if a given object implements the W3CCredentialStatus interface.
 */
export function instanceOfW3CCredentialStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function W3CCredentialStatusFromJSON(json: any): W3CCredentialStatus {
    return W3CCredentialStatusFromJSONTyped(json, false);
}

export function W3CCredentialStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): W3CCredentialStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function W3CCredentialStatusToJSON(value?: W3CCredentialStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'description': value.description,
    };
}

