/* tslint:disable */
/* eslint-disable */
/**
 * PrismAgent OpenAPI specification
 * OpenAPI specification for Decentralized Identifiers (DID) Operations
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: atala-coredid@iohk.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Credential revocation request. Contain credential id and other information required for revocation
 * @export
 * @interface W3CCredentialRevocationRequest
 */
export interface W3CCredentialRevocationRequest {
    /**
     * Credential identity
     * @type {string}
     * @memberof W3CCredentialRevocationRequest
     */
    credentialId: string;
}

/**
 * Check if a given object implements the W3CCredentialRevocationRequest interface.
 */
export function instanceOfW3CCredentialRevocationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "credentialId" in value;

    return isInstance;
}

export function W3CCredentialRevocationRequestFromJSON(json: any): W3CCredentialRevocationRequest {
    return W3CCredentialRevocationRequestFromJSONTyped(json, false);
}

export function W3CCredentialRevocationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): W3CCredentialRevocationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'credentialId': json['credentialId'],
    };
}

export function W3CCredentialRevocationRequestToJSON(value?: W3CCredentialRevocationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'credentialId': value.credentialId,
    };
}

